/* This file is part of 34S.
 * 
 * 34S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * 34S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with 34S.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * This file is automatically generated.
 * Changes will not be preserved.
 */

/*
 * Using a 256 element table to define equivalence classes is smaller
 * than a switch statement to catch the exception.  Lower case is for
 * Greek letters and the Roman letter doesn't correspond at all with the Greek.
 */

/* Maximum distinguished value is 152 */


static const unsigned char character_remapping_order[256] = {
		   0,	  68,	  71,	 135,	 136,	   4,	   0,	 144,	// 0000
		 104,	 124,	 128,	 127,	 132,	 118,	 119,	 121,	// 0010
		 120,	   1,	   2,	   3,	  21,	  52,	  52,	 122,	// 0020
		  58,	  69,	  72,	  44,	 102,	 126,	 133,	 134,	// 0030
		   0,	 107,	 112,	 152,	 131,	 130,	 140,	 111,	// 0040
		  98,	  99,	 113,	 100,	 105,	 101,	 106,	 103,	// 0050
		   4,	   5,	   6,	   7,	   8,	   9,	  10,	  11,	// 0060
		  12,	  13,	 109,	 110,	 123,	 125,	 129,	 108,	// 0070
		 114,	  14,	  20,	  21,	  25,	  27,	  32,	  33,	// 0100
		  34,	  36,	  41,	  42,	  43,	  44,	  45,	  47,	// 0110
		  53,	  54,	  55,	  57,	  59,	  60,	  66,	  67,	// 0120
		  68,	  70,	  73,	 145,	 141,	 146,	 142,	 115,	// 0130
		 151,	  14,	  20,	  21,	  25,	  27,	  32,	  33,	// 0140
		  34,	  36,	  41,	  42,	  43,	  44,	  45,	  47,	// 0150
		  53,	  54,	  55,	  57,	  59,	  60,	  66,	  67,	// 0160
		  68,	  70,	  73,	 147,	 143,	 148,	 116,	 150,	// 0170
		   7,	  67,	  77,	  78,	  26,	  26,	  25,	  82,	// 0200
		  19,	  19,	  85,	  68,	  70,	  88,	 138,	  89,	// 0210
		 113,	  91,	 149,	  54,	  94,	 117,	  96,	  97,	// 0220
		  20,	  86,	   6,	 137,	  68,	 101,	  35,	 137,	// 0230
		  75,	  76,	  77,	  78,	  79,	  80,	  81,	  82,	// 0240
		  83,	  84,	  85,	  86,	  87,	  88,	 139,	  89,	// 0250
		  90,	  91,	  92,	  93,	  94,	  95,	  96,	  97,	// 0260
		   4,	   5,	   6,	  21,	  27,	  45,	  53,	  60,	// 0270
		  15,	  16,	  17,	  18,	  20,	  22,	  23,	  24,	// 0300
		  28,	  29,	  30,	  31,	  37,	  38,	  39,	  40,	// 0310
		  46,	  48,	  49,	  50,	  51,	  56,	  58,	  14,	// 0320
		  61,	  62,	  63,	  64,	  65,	  71,	  72,	  74,	// 0330
		  15,	  16,	  17,	  18,	  20,	  22,	  23,	  24,	// 0340
		  28,	  29,	  30,	  31,	  37,	  38,	  39,	  40,	// 0350
		  46,	  48,	  49,	  50,	  51,	  56,	  58,	  42,	// 0360
		  61,	  62,	  63,	  64,	  65,	  71,	  72,	  74,	// 0370
	};


/* Take a character and remap it into sort order.
 * Also cater for different cases, diacriticals and some
 * special symbols being identical from an ordering perspective.
 */
unsigned char remap_chars(unsigned char ch) {
	return character_remapping_order[ch & 0xff];
}
