/* This file is part of 34S.
 * 
 * 34S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * 34S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with 34S.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * This file is automatically generated.
 * Changes will not be preserved.
 */

/* Mappings from our internal character codes to readable strings.
 * The first table is for characters below space and the second for those
 * >=127 (del).
 */
static const char *const map32[32] = {
	"(null)", "x-bar", "y-bar", "sqrt", "integral", "degree", "narrow-space", "grad",
	"+/-", "<=", ">=", "!=", "euro", "->", "<-", "v",
	"^", "f-shift", "g-shift", "h-shift", "cmplx", "O-slash", "o-slash", "<->",
	"sz", "x-hat", "y-hat", "sub-m", "times", "approx", "pound", "yen",
	};

static const char *const maptop[129] = {
	"^v",
	"^3", "sub-w", "GAMMA", "DELTA", "D-bar", "d-bar", "sub-d", "THETA",
	"AE", "ae", "LAMBDA", "sub-x", "sub-y", "XI", "sol", "PI",
	"super-star", "SIGMA", "print", "sub-q", "PHI", "not", "PSI", "OMEGA",
	"sub-B", "sub-mu", "^2", "sub-infinity", "^x", "^-1", "h-bar", "infinity",
	"alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta",
	"iota", "kappa", "lambda", "mu", "nu", "xi", "terra", "pi",
	"rho", "sigma", "tau", "upsilon", "phi", "chi", "psi", "omega",
	"sub-0", "sub-1", "sub-2", "sub-c", "sub-e", "sub-n", "sub-p", "sub-u",
	"A-grave", "A-acute", "A-circumflex", "A-umlaut", "A-dot", "C-acute", "C-hook", "C-cedilla",
	"E-grave", "E-acute", "E-circumflex", "E-trema", "I-grave", "I-acute", "I-circumflex", "I-trema",
	"N-tilde", "O-grave", "O-acute", "O-circumflex", "O-umlaut", "R-hook", "S-hook", "sub-A",
	"U-grave", "U-acute", "U-circumflex", "U-umlaut", "U-dot", "Y-acute", "Y-trema", "Z-hook",
	"a-grave", "a-acute", "a-circumflex", "a-umlaut", "a-dot", "c-acute", "c-hook", "c-cedilla",
	"e-grave", "e-acute", "e-circumflex", "e-trema", "i-grave", "i-acute", "i-circumflex", "i-trema",
	"n-tilde", "o-grave", "o-acute", "o-circumflex", "o-umlaut", "r-hook", "s-hook", "sub-k",
	"u-grave", "u-acute", "u-circumflex", "u-umlaut", "u-dot", "y-acute", "y-trema", "z-hook",
	};

