/* This file is part of 34S.
 * 
 * 34S is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * 34S is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with 34S.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * 
 * This file is automatically generated.
 * Changes will not be preserved.
 */

/* Tables to map to Unicode and Windows CP1252 (sort of)
 */

const int unicode[256] = {
	0x0000,	// (null)
	0x1e80,	// x-bar
	0x0233,	// y-bar
	0x221a,	// sqrt
	0x222b,	// integral
	0x00b0,	// degree
	0x00a0,	// narrow-space
	0x24bc,	// grad
	0x00b1,	// +/-
	0x2264,	// <=
	0x2265,	// >=
	0x2260,	// !=
	0x20ac,	// euro
	0x2192,	// ->
	0x2190,	// <-
	0x2193,	// v
	0x2191,	// ^
	0x24d5,	// f-shift
	0x24d6,	// g-shift
	0x24d7,	// h-shift
	0x00a9,	// cmplx
	0x00d8,	// O-slash
	0x00f8,	// o-slash
	0x21c6,	// <->
	0x00df,	// sz
	0x1e8b,	// x-hat
	0x0177,	// y-hat
	0x2098,	// sub-m
	0x00d7,	// times
	0x2248,	// approx
	0x00a3,	// pound
	0x00a5,	// yen
	0x0020,	// space
	0x0021,	// !
	0x0022,	// dbl-quote
	0x0023,	// #
	0x0024,	// $
	0x0025,	// %
	0x0026,	// &
	0x0027,	// '
	0x0028,	// (
	0x0029,	// )
	0x002a,	// *
	0x002b,	// +
	0x002c,	// ,
	0x002d,	// -
	0x002e,	// .
	0x002f,	// /
	0x0030,	// 0
	0x0031,	// 1
	0x0032,	// 2
	0x0033,	// 3
	0x0034,	// 4
	0x0035,	// 5
	0x0036,	// 6
	0x0037,	// 7
	0x0038,	// 8
	0x0039,	// 9
	0x003a,	// :
	0x003b,	// ;
	0x003c,	// <
	0x003d,	// =
	0x003e,	// >
	0x003f,	// ?
	0x0040,	// @
	0x0041,	// A
	0x0042,	// B
	0x0043,	// C
	0x0044,	// D
	0x0045,	// E
	0x0046,	// F
	0x0047,	// G
	0x0048,	// H
	0x0049,	// I
	0x004a,	// J
	0x004b,	// K
	0x004c,	// L
	0x004d,	// M
	0x004e,	// N
	0x004f,	// O
	0x0050,	// P
	0x0051,	// Q
	0x0052,	// R
	0x0053,	// S
	0x0054,	// T
	0x0055,	// U
	0x0056,	// V
	0x0057,	// W
	0x0058,	// X
	0x0059,	// Y
	0x005a,	// Z
	0x005b,	// [
	0x005c,	// backslash
	0x005d,	// ]
	0x005e,	// ^
	0x005f,	// _
	0x0060,	// back-quote
	0x0061,	// a
	0x0062,	// b
	0x0063,	// c
	0x0064,	// d
	0x0065,	// e
	0x0066,	// f
	0x0067,	// g
	0x0068,	// h
	0x0069,	// i
	0x006a,	// j
	0x006b,	// k
	0x006c,	// l
	0x006d,	// m
	0x006e,	// n
	0x006f,	// o
	0x0070,	// p
	0x0071,	// q
	0x0072,	// r
	0x0073,	// s
	0x0074,	// t
	0x0075,	// u
	0x0076,	// v
	0x0077,	// w
	0x0078,	// x
	0x0079,	// y
	0x007a,	// z
	0x007b,	// {
	0x007c,	// |
	0x007d,	// }
	0x007e,	// ~
	0x2195,	// ^v
	0x00b3,	// ^3
	0x24b2,	// sub-w
	0x0393,	// GAMMA
	0x0394,	// DELTA
	0x00d0,	// D-bar
	0x00f0,	// d-bar
	0x249f,	// sub-d
	0x0398,	// THETA
	0x00c6,	// AE
	0x00e6,	// ae
	0x039b,	// LAMBDA
	0x2093,	// sub-x
	0x1d67,	// sub-y
	0x039e,	// XI
	0x2609,	// sol
	0x03a0,	// PI
	0x207a,	// super-star
	0x03a3,	// SIGMA
	0x2399,	// print
	0x209b,	// sub-q
	0x03a6,	// PHI
	0x00ac,	// not
	0x03a8,	// PSI
	0x03a9,	// OMEGA
	0x249d,	// sub-B
	0x00b6,	// sub-mu
	0x00b2,	// ^2
	0x2088,	// sub-infinity
	0x1d61,	// ^x
	0x2078,	// ^-1
	0x0127,	// h-bar
	0x221e,	// infinity
	0x03b1,	// alpha
	0x03b2,	// beta
	0x03b3,	// gamma
	0x03b4,	// delta
	0x03b5,	// epsilon
	0x03b6,	// zeta
	0x03b7,	// eta
	0x03b8,	// theta
	0x03b9,	// iota
	0x03ba,	// kappa
	0x03bb,	// lambda
	0x03bc,	// mu
	0x03bd,	// nu
	0x03be,	// xi
	0x2641,	// terra
	0x03c0,	// pi
	0x03c1,	// rho
	0x03c3,	// sigma
	0x03c4,	// tau
	0x03c5,	// upsilon
	0x03c6,	// phi
	0x03c7,	// chi
	0x03c8,	// psi
	0x03c9,	// omega
	0x2080,	// sub-0
	0x2081,	// sub-1
	0x2082,	// sub-2
	0x249e,	// sub-c
	0x2091,	// sub-e
	0x2099,	// sub-n
	0x209a,	// sub-p
	0x1d64,	// sub-u
	0x00c0,	// A-grave
	0x00c1,	// A-acute
	0x00c2,	// A-circumflex
	0x00c4,	// A-umlaut
	0x00c5,	// A-dot
	0x0106,	// C-acute
	0x010c,	// C-hook
	0x00c7,	// C-cedilla
	0x00c8,	// E-grave
	0x00c9,	// E-acute
	0x00ca,	// E-circumflex
	0x00cb,	// E-trema
	0x00cc,	// I-grave
	0x00cd,	// I-acute
	0x00ce,	// I-circumflex
	0x00cf,	// I-trema
	0x00d1,	// N-tilde
	0x00d2,	// O-grave
	0x00d3,	// O-acute
	0x00d4,	// O-circumflex
	0x00d6,	// O-umlaut
	0x0158,	// R-hook
	0x0160,	// S-hook
	0x2090,	// sub-A
	0x00d9,	// U-grave
	0x00da,	// U-acute
	0x00db,	// U-circumflex
	0x00dc,	// U-umlaut
	0x016e,	// U-dot
	0x00dd,	// Y-acute
	0x0178,	// Y-trema
	0x017d,	// Z-hook
	0x00e0,	// a-grave
	0x00e1,	// a-acute
	0x00e2,	// a-circumflex
	0x00e4,	// a-umlaut
	0x00e5,	// a-dot
	0x0107,	// c-acute
	0x010d,	// c-hook
	0x00e7,	// c-cedilla
	0x00e8,	// e-grave
	0x00e9,	// e-acute
	0x00ea,	// e-circumflex
	0x00eb,	// e-trema
	0x00ec,	// i-grave
	0x00ed,	// i-acute
	0x00ee,	// i-circumflex
	0x00ef,	// i-trema
	0x00f1,	// n-tilde
	0x00f2,	// o-grave
	0x00f3,	// o-acute
	0x00f4,	// o-circumflex
	0x00f6,	// o-umlaut
	0x0159,	// r-hook
	0x0161,	// s-hook
	0x2096,	// sub-k
	0x00f9,	// u-grave
	0x00fa,	// u-acute
	0x00fb,	// u-circumflex
	0x00fc,	// u-umlaut
	0x016f,	// u-dot
	0x00fd,	// y-acute
	0x00ff,	// y-trema
	0x017e,	// z-hook
};

const unsigned char to_cp1252[256] = {
	0x00,	// (null) (undefined)
	0x00,	// x-bar (undefined)
	0x00,	// y-bar (undefined)
	0x00,	// sqrt (undefined)
	0x00,	// integral (undefined)
	0xb0,	// degree 
	0xa0,	// narrow-space 
	0x00,	// grad (undefined)
	0xb1,	// +/- 
	0xab,	// <= 
	0xbb,	// >= 
	0x87,	// != 
	0x80,	// euro 
	0x00,	// -> (undefined)
	0x00,	// <- (undefined)
	0x00,	// v (undefined)
	0x00,	// ^ (undefined)
	0x00,	// f-shift (undefined)
	0x00,	// g-shift (undefined)
	0x00,	// h-shift (undefined)
	0xa9,	// cmplx 
	0xd8,	// O-slash 
	0xf8,	// o-slash 
	0x00,	// <-> (undefined)
	0xdf,	// sz 
	0x00,	// x-hat (undefined)
	0x00,	// y-hat (undefined)
	0x00,	// sub-m (undefined)
	0xd7,	// times 
	0x00,	// approx (undefined)
	0xa3,	// pound 
	0xa5,	// yen 
	0x20,	// space 
	0x21,	// ! 
	0x22,	// dbl-quote 
	0x23,	// # 
	0x24,	// $ 
	0x25,	// % 
	0x26,	// & 
	0x27,	// ' 
	0x28,	// ( 
	0x29,	// ) 
	0x2a,	// * 
	0x2b,	// + 
	0x2c,	// , 
	0x2d,	// - 
	0x2e,	// . 
	0x2f,	// / 
	0x30,	// 0 
	0x31,	// 1 
	0x32,	// 2 
	0x33,	// 3 
	0x34,	// 4 
	0x35,	// 5 
	0x36,	// 6 
	0x37,	// 7 
	0x38,	// 8 
	0x39,	// 9 
	0x3a,	// : 
	0x3b,	// ; 
	0x3c,	// < 
	0x3d,	// = 
	0x3e,	// > 
	0x3f,	// ? 
	0x40,	// @ 
	0x41,	// A 
	0x42,	// B 
	0x43,	// C 
	0x44,	// D 
	0x45,	// E 
	0x46,	// F 
	0x47,	// G 
	0x48,	// H 
	0x49,	// I 
	0x4a,	// J 
	0x4b,	// K 
	0x4c,	// L 
	0x4d,	// M 
	0x4e,	// N 
	0x4f,	// O 
	0x50,	// P 
	0x51,	// Q 
	0x52,	// R 
	0x53,	// S 
	0x54,	// T 
	0x55,	// U 
	0x56,	// V 
	0x57,	// W 
	0x58,	// X 
	0x59,	// Y 
	0x5a,	// Z 
	0x5b,	// [ 
	0x5c,	// backslash 
	0x5d,	// ] 
	0x5e,	// ^ 
	0x5f,	// _ 
	0x60,	// back-quote 
	0x61,	// a 
	0x62,	// b 
	0x63,	// c 
	0x64,	// d 
	0x65,	// e 
	0x66,	// f 
	0x67,	// g 
	0x68,	// h 
	0x69,	// i 
	0x6a,	// j 
	0x6b,	// k 
	0x6c,	// l 
	0x6d,	// m 
	0x6e,	// n 
	0x6f,	// o 
	0x70,	// p 
	0x71,	// q 
	0x72,	// r 
	0x73,	// s 
	0x74,	// t 
	0x75,	// u 
	0x76,	// v 
	0x77,	// w 
	0x78,	// x 
	0x79,	// y 
	0x7a,	// z 
	0x7b,	// { 
	0x7c,	// | 
	0x7d,	// } 
	0x7e,	// ~ 
	0x7f,	// ^v 
	0xb3,	// ^3 
	0x00,	// sub-w (undefined)
	0x00,	// GAMMA (undefined)
	0x00,	// DELTA (undefined)
	0xd0,	// D-bar 
	0xf0,	// d-bar 
	0x0e,	// sub-d 
	0x00,	// THETA (undefined)
	0xc6,	// AE 
	0xe6,	// ae 
	0x00,	// LAMBDA (undefined)
	0x08,	// sub-x 
	0x09,	// sub-y 
	0x00,	// XI (undefined)
	0x00,	// sol (undefined)
	0x00,	// PI (undefined)
	0xa4,	// super-star 
	0x00,	// SIGMA (undefined)
	0x0c,	// print 
	0x0a,	// sub-q 
	0x00,	// PHI (undefined)
	0xac,	// not 
	0x00,	// PSI (undefined)
	0x00,	// OMEGA (undefined)
	0x00,	// sub-B (undefined)
	0x00,	// sub-mu (undefined)
	0xb2,	// ^2 
	0x00,	// sub-infinity (undefined)
	0x00,	// ^x (undefined)
	0x00,	// ^-1 (undefined)
	0x00,	// h-bar (undefined)
	0x00,	// infinity (undefined)
	0x00,	// alpha (undefined)
	0x00,	// beta (undefined)
	0x00,	// gamma (undefined)
	0x00,	// delta (undefined)
	0x00,	// epsilon (undefined)
	0x00,	// zeta (undefined)
	0x00,	// eta (undefined)
	0x00,	// theta (undefined)
	0x00,	// iota (undefined)
	0x00,	// kappa (undefined)
	0x00,	// lambda (undefined)
	0xb5,	// mu 
	0x00,	// nu (undefined)
	0x00,	// xi (undefined)
	0x00,	// terra (undefined)
	0x00,	// pi (undefined)
	0x00,	// rho (undefined)
	0x00,	// sigma (undefined)
	0x00,	// tau (undefined)
	0x00,	// upsilon (undefined)
	0x00,	// phi (undefined)
	0x00,	// chi (undefined)
	0x00,	// psi (undefined)
	0x00,	// omega (undefined)
	0x00,	// sub-0 (undefined)
	0x00,	// sub-1 (undefined)
	0x00,	// sub-2 (undefined)
	0x00,	// sub-c (undefined)
	0x00,	// sub-e (undefined)
	0x00,	// sub-n (undefined)
	0x00,	// sub-p (undefined)
	0x00,	// sub-u (undefined)
	0xc0,	// A-grave 
	0xc1,	// A-acute 
	0xc2,	// A-circumflex 
	0xc4,	// A-umlaut 
	0xc5,	// A-dot 
	0x00,	// C-acute (undefined)
	0x00,	// C-hook (undefined)
	0xc7,	// C-cedilla 
	0xc8,	// E-grave 
	0xc9,	// E-acute 
	0xca,	// E-circumflex 
	0xcb,	// E-trema 
	0xcc,	// I-grave 
	0xcd,	// I-acute 
	0xce,	// I-circumflex 
	0xcf,	// I-trema 
	0xd1,	// N-tilde 
	0xd2,	// O-grave 
	0xd3,	// O-acute 
	0xd4,	// O-circumflex 
	0xd6,	// O-umlaut 
	0x00,	// R-hook (undefined)
	0x8a,	// S-hook 
	0x00,	// sub-A (undefined)
	0xd9,	// U-grave 
	0xda,	// U-acute 
	0xdb,	// U-circumflex 
	0xdc,	// U-umlaut 
	0x00,	// U-dot (undefined)
	0xdd,	// Y-acute 
	0x9f,	// Y-trema 
	0x8e,	// Z-hook 
	0xe0,	// a-grave 
	0xe1,	// a-acute 
	0xe2,	// a-circumflex 
	0xe4,	// a-umlaut 
	0xe5,	// a-dot 
	0x00,	// c-acute (undefined)
	0x00,	// c-hook (undefined)
	0xe7,	// c-cedilla 
	0xe8,	// e-grave 
	0xe9,	// e-acute 
	0xea,	// e-circumflex 
	0xeb,	// e-trema 
	0xec,	// i-grave 
	0xed,	// i-acute 
	0xee,	// i-circumflex 
	0xef,	// i-trema 
	0xf1,	// n-tilde 
	0xf2,	// o-grave 
	0xf3,	// o-acute 
	0xf4,	// o-circumflex 
	0xf6,	// o-umlaut 
	0x00,	// r-hook (undefined)
	0x9a,	// s-hook 
	0x00,	// sub-k (undefined)
	0xf9,	// u-grave 
	0xfa,	// u-acute 
	0xfb,	// u-circumflex 
	0xfc,	// u-umlaut 
	0x00,	// u-dot (undefined)
	0xfd,	// y-acute 
	0xff,	// y-trema 
	0x9e,	// z-hook 
};

const unsigned char from_cp1252[256] = {
	0xfc,	// u-dot
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x8b,	// sub-x
	0x8c,	// sub-y
	0x93,	// sub-q
	0x00,	// (null)
	0x92,	// print
	0x00,	// (null)
	0x86,	// sub-d
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x20,	// space
	0x21,	// !
	0x22,	// dbl-quote
	0x23,	// #
	0x24,	// $
	0x25,	// %
	0x26,	// &
	0x27,	// '
	0x28,	// (
	0x29,	// )
	0x2a,	// *
	0x2b,	// +
	0x2c,	// ,
	0x2d,	// -
	0x2e,	// .
	0x2f,	// /
	0x30,	// 0
	0x31,	// 1
	0x32,	// 2
	0x33,	// 3
	0x34,	// 4
	0x35,	// 5
	0x36,	// 6
	0x37,	// 7
	0x38,	// 8
	0x39,	// 9
	0x3a,	// :
	0x3b,	// ;
	0x3c,	// <
	0x3d,	// =
	0x3e,	// >
	0x3f,	// ?
	0x40,	// @
	0x41,	// A
	0x42,	// B
	0x43,	// C
	0x44,	// D
	0x45,	// E
	0x46,	// F
	0x47,	// G
	0x48,	// H
	0x49,	// I
	0x4a,	// J
	0x4b,	// K
	0x4c,	// L
	0x4d,	// M
	0x4e,	// N
	0x4f,	// O
	0x50,	// P
	0x51,	// Q
	0x52,	// R
	0x53,	// S
	0x54,	// T
	0x55,	// U
	0x56,	// V
	0x57,	// W
	0x58,	// X
	0x59,	// Y
	0x5a,	// Z
	0x5b,	// [
	0x5c,	// backslash
	0x5d,	// ]
	0x5e,	// ^
	0x5f,	// _
	0x60,	// back-quote
	0x61,	// a
	0x62,	// b
	0x63,	// c
	0x64,	// d
	0x65,	// e
	0x66,	// f
	0x67,	// g
	0x68,	// h
	0x69,	// i
	0x6a,	// j
	0x6b,	// k
	0x6c,	// l
	0x6d,	// m
	0x6e,	// n
	0x6f,	// o
	0x70,	// p
	0x71,	// q
	0x72,	// r
	0x73,	// s
	0x74,	// t
	0x75,	// u
	0x76,	// v
	0x77,	// w
	0x78,	// x
	0x79,	// y
	0x7a,	// z
	0x7b,	// {
	0x7c,	// |
	0x7d,	// }
	0x7e,	// ~
	0x7f,	// ^v
	0x0c,	// euro
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x0b,	// !=
	0x00,	// (null)
	0x00,	// (null)
	0xd6,	// S-hook
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0xdf,	// Z-hook
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0xf6,	// s-hook
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0xff,	// z-hook
	0xde,	// Y-trema
	0x06,	// narrow-space
	0x00,	// (null)
	0x00,	// (null)
	0x1e,	// pound
	0x90,	// super-star
	0x1f,	// yen
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x14,	// cmplx
	0x00,	// (null)
	0x09,	// <=
	0x95,	// not
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x05,	// degree
	0x08,	// +/-
	0x9a,	// ^2
	0x80,	// ^3
	0x00,	// (null)
	0xab,	// mu
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x0a,	// >=
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0x00,	// (null)
	0xc0,	// A-grave
	0xc1,	// A-acute
	0xc2,	// A-circumflex
	0x00,	// (null)
	0xc3,	// A-umlaut
	0xc4,	// A-dot
	0x88,	// AE
	0xc7,	// C-cedilla
	0xc8,	// E-grave
	0xc9,	// E-acute
	0xca,	// E-circumflex
	0xcb,	// E-trema
	0xcc,	// I-grave
	0xcd,	// I-acute
	0xce,	// I-circumflex
	0xcf,	// I-trema
	0x84,	// D-bar
	0xd0,	// N-tilde
	0xd1,	// O-grave
	0xd2,	// O-acute
	0xd3,	// O-circumflex
	0x00,	// (null)
	0xd4,	// O-umlaut
	0x1c,	// times
	0x15,	// O-slash
	0xd8,	// U-grave
	0xd9,	// U-acute
	0xda,	// U-circumflex
	0xdb,	// U-umlaut
	0xdd,	// Y-acute
	0x00,	// (null)
	0x18,	// sz
	0xe0,	// a-grave
	0xe1,	// a-acute
	0xe2,	// a-circumflex
	0x00,	// (null)
	0xe3,	// a-umlaut
	0xe4,	// a-dot
	0x89,	// ae
	0xe7,	// c-cedilla
	0xe8,	// e-grave
	0xe9,	// e-acute
	0xea,	// e-circumflex
	0xeb,	// e-trema
	0xec,	// i-grave
	0xed,	// i-acute
	0xee,	// i-circumflex
	0xef,	// i-trema
	0x85,	// d-bar
	0xf0,	// n-tilde
	0xf1,	// o-grave
	0xf2,	// o-acute
	0xf3,	// o-circumflex
	0x00,	// (null)
	0xf4,	// o-umlaut
	0x00,	// (null)
	0x16,	// o-slash
	0xf8,	// u-grave
	0xf9,	// u-acute
	0xfa,	// u-circumflex
	0xfb,	// u-umlaut
	0xfd,	// y-acute
	0x00,	// (null)
	0xfe,	// y-trema
};

const char *charnames[256] = {
	"(null)",
	"x-bar",
	"y-bar",
	"sqrt",
	"integral",
	"degree",
	"narrow-space",
	"grad",
	"plus-minus",
	"le",
	"ge",
	"ne",
	"euro",
	"right",
	"left",
	"down",
	"up",
	"f-shift",
	"g-shift",
	"h-shift",
	"cmplx",
	"O-slash",
	"o-slash",
	"exchange",
	"sz",
	"x-hat",
	"y-hat",
	"sub-m",
	"times",
	"approx",
	"pound",
	"yen",
	"space",
	"exclam",
	"quotedbl",
	"numbersign",
	"dollar",
	"percent",
	"ampersand",
	"quotesingle",
	"parenleft",
	"parenright",
	"asterisk",
	"plus",
	"comma",
	"hyphen",
	"period",
	"slash",
	"zero",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
	"colon",
	"semicolon",
	"less",
	"equal",
	"greater",
	"question",
	"at",
	"A",
	"B",
	"C",
	"D",
	"E",
	"F",
	"G",
	"H",
	"I",
	"J",
	"K",
	"L",
	"M",
	"N",
	"O",
	"P",
	"Q",
	"R",
	"S",
	"T",
	"U",
	"V",
	"W",
	"X",
	"Y",
	"Z",
	"bracketleft",
	"backslash",
	"bracketright",
	"asciicircum",
	"underscore",
	"accentgrave",
	"a",
	"b",
	"c",
	"d",
	"e",
	"f",
	"g",
	"h",
	"i",
	"j",
	"k",
	"l",
	"m",
	"n",
	"o",
	"p",
	"q",
	"r",
	"s",
	"t",
	"u",
	"v",
	"w",
	"x",
	"y",
	"z",
	"braceleft",
	"bar",
	"braceright",
	"asciitilde",
	"up-down",
	"super-3",
	"sub-w",
	"GAMMA",
	"DELTA",
	"D-bar",
	"d-bar",
	"sub-d",
	"THETA",
	"AE",
	"ae",
	"LAMBDA",
	"sub-x",
	"sub-y",
	"XI",
	"sol",
	"PI",
	"super-star",
	"SIGMA",
	"printscreensymbol",
	"sub-q",
	"PHI",
	"not",
	"PSI",
	"OMEGA",
	"sub-B",
	"sub-mu",
	"super-2",
	"sub-infinity",
	"super-x",
	"reciprocal",
	"h-bar",
	"infinity",
	"alpha",
	"beta",
	"gamma",
	"delta",
	"epsilon",
	"zeta",
	"eta",
	"theta",
	"iota",
	"kappa",
	"lambda",
	"mu",
	"nu",
	"xi",
	"terra",
	"pi",
	"rho",
	"sigma",
	"tau",
	"upsilon",
	"phi",
	"chi",
	"psi",
	"omega",
	"sub-0",
	"sub-1",
	"sub-2",
	"sub-c",
	"sub-e",
	"sub-n",
	"sub-p",
	"sub-u",
	"A-grave",
	"A-acute",
	"A-circumflex",
	"A-umlaut",
	"A-dot",
	"C-acute",
	"C-hook",
	"C-cedilla",
	"E-grave",
	"E-acute",
	"E-circumflex",
	"E-trema",
	"I-grave",
	"I-acute",
	"I-circumflex",
	"I-trema",
	"N-tilde",
	"O-grave",
	"O-acute",
	"O-circumflex",
	"O-umlaut",
	"R-hook",
	"S-hook",
	"sub-A",
	"U-grave",
	"U-acute",
	"U-circumflex",
	"U-umlaut",
	"U-dot",
	"Y-acute",
	"Y-trema",
	"Z-hook",
	"a-grave",
	"a-acute",
	"a-circumflex",
	"a-umlaut",
	"a-dot",
	"c-acute",
	"c-hook",
	"c-cedilla",
	"e-grave",
	"e-acute",
	"e-circumflex",
	"e-trema",
	"i-grave",
	"i-acute",
	"i-circumflex",
	"i-trema",
	"n-tilde",
	"o-grave",
	"o-acute",
	"o-circumflex",
	"o-umlaut",
	"r-hook",
	"s-hook",
	"sub-k",
	"u-grave",
	"u-acute",
	"u-circumflex",
	"u-umlaut",
	"u-dot",
	"y-acute",
	"y-trema",
	"z-hook",
};

